<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="del1-lhp-N01966" ignored="0" name="Copy_of_Pixel_2" tests="3" failures="1" timestamp="11 Aug 2020 16:13:14 GMT" time="85.291" errors="0">
  <testcase name="invalidPassword" time="6.472" classname="com.qa.mobile.testcases.LoginTests"/>
  <testcase name="invalidUserName" time="4.778" classname="com.qa.mobile.testcases.LoginTests">
    <failure type="java.lang.AssertionError" message="expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.sdfdf]">
      <![CDATA[java.lang.AssertionError: expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.sdfdf]
at com.qa.mobile.testcases.LoginTests.invalidUserName(LoginTests.java:74)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- invalidUserName -->
  <testcase name="successfulLogin" time="7.384" classname="com.qa.mobile.testcases.LoginTests"/>
</testsuite> <!-- Copy_of_Pixel_2 -->
